global:
  imagePullPolicy: Always
  #vault:
  #  host: ip
  #  name: vault
  #  vaultToken: someToken


frontend:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: kirillpudov.students-projects.ru
    path: /
    pathType: Prefix
  containerPort: 80
  image: kirillpudov/sausage-frontend:latest
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    reportPath: /logs/reports
    logPath: /logs
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  image: kirillpudov/sausage-backend:latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "1"
  containerPort: 8080
  livenessProbe:
    exec:
      command:
        - ls
    initialDelaySeconds: 15
    periodSeconds: 10
  vpa:
    updatePolicy:
      updateMode: "Auto"
    resourcePolicy:
      containerPolicies:
      - containerName: "*"
        controlledResources: ["cpu", "memory"]

backend-report:
  image: kirillpudov/sausage-backend-report:latest
  revisionHistoryLimit: 15
  replicas: 1
  containerPort: 8080
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"
  strategy:
    type: Recreate
  service:
    port: 8080
  livenessProbe:
    httpGet:
      path: /api/v1/health
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 10
  hpa:
    minReplicas: 1
    maxReplicas: 1
    averageUtilization: 75

infra:
  postgres:
    env:
      POSTGRES_PASSWORD: storepassword
      POSTGRES_USER: store
      POSTGRES_DB: sausage-store
    containerPort: 5432
  mongodb:
    env:
      MONGO_INITDB_ROOT_USERNAME: reports
      MONGO_INITDB_ROOT_PASSWORD: reportspassword
      MONGO_INITDB_DATABASE: sausage-store
    containerPort: 27017
